version: "3.4"
services:
    nginx:
        build: ./nginx
        image: z_nginx:1.12.2
        ports:
            - "80:80"
            - "433:443"
            - "7000:7000"
            - "8000:8000"
        volumes:
            - ./nginx/conf/nginx.conf:/etc/nginx/nginx.conf:ro #nginx配置
            - ./nginx/conf/sites-enabled:/etc/nginx/sites-enabled:ro #site配置
            - ./nginx/logs:/var/log/nginx #日志目录
            - ~/htdocs/:/opt/htdocs/ #项目目录
        links:
            - "php"
    php:
        build: ./php
        image: z_php:7.0-fpm
        ports:
            - "9000:9000"
        volumes:
            - ~/htdocs/:/opt/htdocs/ #项目目录, 需与nginx的项目目录相同，才有权限访问
        links:
            - "mysql"

    mysql:
        build: ./mysql_alphine
        image: z_mysql:alphine
        ports:
            - "3306:3306"
        volumes:
            - ./mysql_alphine/data:/var/lib/mysql
        environment:
            MYSQL_ROOT_PASSWORD: root
